sequenceDiagram;
    participant User;
    participant Dapp;
	participant NewPay;
	participant HEP API;

	User->>NewPay: Open Dapp Store;
	User->>NewPay: Install Dapp;
	User-->>Dapp: Open Dapp
	Dapp->>NewPay: Request NewID access
	NewPay->>HEP API: Send Dapp public key;
	HEP API->>NewPay: Send Dapp info, request user access;
	NewPay->>User: Pop-up requesting NewID
	User->>NewPay: Authorize access
	NewPay->>Dapp: NewID sent to Dapp;
	NewPay-->>Dapp: Send user back;
