sequenceDiagram;
    participant User;
    participant Native Dapp;
	participant NewPay;
	participant HEP API;
    User->>Native Dapp: Click Login;
	Native Dapp->>NewPay: Send login request;
	NewPay->>HEP API: Send Dapp public key;
	HEP API->>NewPay: Send Dapp info, request user access;
	NewPay->> User: Prompt to authorize login;
	User->>NewPay: Authorize login;
	NewPay->>Native Dapp: NewID sent to Dapp;
	NewPay-->>Native Dapp: Send user back;
